version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hotel_bookings_management_db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./HotelBookingsManagement_schema.sql:/docker-entrypoint-initdb.d/HotelBookingsManagement_schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: